name: gym-http-api
version: '0.1.0.0'
description: Haskell binding for the OpenAi gym API
category: Web, Learning Environments
author: Daniel Lucsanszky, Sam Stites
maintainer: dl3913@ic.ac.uk, sam@stites.io
license: MIT
license-file: LICENSE
github: stites/gym-http-api/binding-hs
synopsis: REST client to the gym-http-api project
description: This library provides a REST client to the gym open-source library. gym-http-api itself provides a local REST API to the gym open-source library, allowing development in languages other than python.
extra-source-files:
- README.md

default-extensions:
  - OverloadedStrings

dependencies:
  - base           >= 4.7 && < 5
  - servant-client >= 0.9

library:
  source-dirs: src
  dependencies:
  - aeson                >= 1.0
  - unordered-containers >= 0.2
  - servant              >= 0.9
  - servant-lucid        >= 0.7
  - text                 >= 1.2

executables:
  example:
    main: Agent.hs
    source-dirs: examples
    dependencies:
    - gym-http-api
    - http-client    >= 0.5
    - exceptions     >= 0.8

# tests:
  # binding-hs-test:
    # main: Spec.hs
    # source-dirs: test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-K1K
    # dependencies:
    # - base
    # - binding-hs
